# Generated by Django 3.0.4 on 2020-03-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_board_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='age',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
