# Generated by Django 3.0.4 on 2020-03-26 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_board_main', '0002_auto_20200326_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='email',
        ),
    ]
