# Generated by Django 3.0.2 on 2020-02-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_auto_20200224_1310"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
