# Generated by Django 3.0.2 on 2020-02-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_auto_20200227_1045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
