# Generated by Django 3.0.2 on 2020-02-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_auto_20200227_1151"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(verbose_name="date"),
        ),
    ]
