# Generated by Django 3.0.2 on 2020-02-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_auto_20200228_1311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="blog_photo",
            field=models.ImageField(blank=True, null=True, upload_to="blogs"),
        ),
    ]
