# Generated by Django 3.0.2 on 2020-01-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="award_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="award",
            name="award_detail",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="educationalbackground",
            name="school_type",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="project", name="project_description", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_photo",
            field=models.ImageField(blank=True, null=True, upload_to="projects"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="skill_photo",
            field=models.ImageField(blank=True, default="", upload_to="skills"),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="location",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
