# Generated by Django 3.0.2 on 2020-01-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_auto_20200130_1452"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_photo",
            field=models.ImageField(blank=True, default="", upload_to="projects"),
        ),
    ]
