# Generated by Django 3.0.2 on 2020-01-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_auto_20200130_1519"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_photo",
            field=models.ImageField(blank=True, null=True, upload_to="projects"),
        ),
    ]
