# Generated by Django 3.0.2 on 2020-02-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_auto_20200130_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.TextField(default="Write something about yourself"),
        ),
    ]
