# Generated by Django 3.0.2 on 2020-02-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_auto_20200210_1145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_photo",
            field=models.ImageField(null=True, upload_to="profile_pics"),
        ),
    ]
