# Generated by Django 3.0.2 on 2020-02-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_auto_20200211_1544"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
