# Generated by Django 3.0.2 on 2020-02-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_auto_20200211_1600"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("address", "Address"),
                    ("website", "Website"),
                    ("email", "Email Address"),
                    ("mobile", "Mobile"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.TextField(default="Write something about yourself"),
        ),
    ]
