# Generated by Django 3.0.2 on 2020-02-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_auto_20200219_1055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.TextField(blank=True, default=""),
        ),
    ]
