# Generated by Django 3.0.2 on 2020-03-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_auto_20200220_1739"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_photo",
            field=models.ImageField(null=True, upload_to="profile_pics"),
        ),
    ]
